openapi: 3.0.3
info:
  title: User API
  version: '1.0'
  description: This is a simple API for creating users.
  license:
    name: TBD
    url: https://redocly.com/subscription-agreement/
security: []
servers:
  - url: https://open-api.onrender.com
    description: Production server
  - url: http://localhost:3000
    description: Local server
paths:
  /user:
    $ref: paths/user.yaml
  /user/{id}:
    $ref: paths/user{id}.yaml
